### ISSUE TITLE
Rip out all the cruft from the Notification structure

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#189]
For some reason, when I wrote the `Notification` struct, I assumed serde would fail to deserialize if I hadn't defined every single property that AWS sets on the object. But of course it doesn't, it just skips over any that aren't defined on the target object.

We should remove all the unused properties from our `Notification` struct and make that module much, much shorter.

**Comment by brizental** [comment]
I can work on this, since I just looked at it for writing the tests :)

There is actually a lot of extra stuff that we don't use anywhere else in the code. For instance the whole `Mail` struct (https://github.com/mozilla/fxa-email-service/blob/master/src/queues/sqs/notification/mod.rs#L130) is not used anywhere else. I guess we do want some of it for checking in case something goes wrong, but most of it is unnecessary. 

Also inside the `delivery`, `bounce` and `complaint` parts we probably just want the timestamp, recipient and bounce/complaint record. Sounds about right? @philbooth

**Comment by brizental** [comment]
> For instance the whole Mail struct (https://github.com/mozilla/fxa-email-service/blob/master/src/queues/sqs/notification/mod.rs#L130) is not used anywhere else.

This was wrong. We do use `source`, `headers`, `destination` and `message_id`: https://github.com/mozilla/fxa-email-service/blob/master/src/queues/sqs/notification/mod.rs#L152-L156
