### ISSUE TITLE
Add headers option to /send POST params

### ISSUE THREAD

**Issue by brizental** [mozilla/fxa-email-service#75]
This came up when I was looking at #46 .

We add some custom headers to our emails (https://github.com/mozilla/fxa-auth-server/blob/master/test/mail_helper.js#L42-L48), and right now we don't have an option to do that with this service. The new option would look like this: 

```
curl \
  -d '{"to":"foo@example.com","subject":"bar","headers": {"x-whatever": "blablabla"},"body":{"text":"baz"}}' \
  -H 'Content-Type: application/json' \
  http://localhost:8001/send
```

I sent a PR to the sendgrid-rs package, adding an `add_headers` function to the personalizations (https://github.com/gsquire/sendgrid-rs/pull/26), so that should be easy enough.

The SES though, would need to be refactored to use `SendRawEmailRequest` (https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html) instead of `SendEmailRequest`, which is what we are using right now and doesn't accept custom headers.

**Comment by philbooth** [comment]
@brizental I don't think we need to worry about this.

Afaik, those headers are only used as a hack for propagating state to the bounce/complaint/delivery notifications. In this repo we are replacing it with proper storage keyed by the message id, as per #72 and #73. Although maybe @vbudhram or @vladikoff can set me straight if there are other legitimate uses for them.

Good thinking though! :smile:

**Comment by philbooth** [comment]
>  we send template names

Can't those go in Redis as part of the metadata blob?

> we needed for the STDOUT provider

Why though? That provider can have a delivery queue stub that works just like the other providers, reading data from Redis, can't it?

**Comment by vladikoff** [comment]
@philbooth don't we use those like everywhere: https://github.com/mozilla/fxa-auth-server/blob/677bdbb6a80da2f4160cf47fc129eb5a43b9f8ee/test/mail_helper.js#L42 I find them very useful, we don't have to include the bounce headers hacks in this though

**Comment by philbooth** [comment]
I'd prefer if there was just one mechanism for associating data with a message, because it makes both the code and the API simpler. For the mail helper, that would mean there is some refactoring to do for it to use the API we've specced out here. The alternative, of refactoring here so that the mail helper can remain unchanged feels like a poor tradeoff to me. A third option, which I'd also be comfortable with, is just to keep the mail helper completely separate to this repo and don't both with adding a logging provider implementation here.

In the code you link to, it looks like those headers are just sent to the logs. That seems straightforward enough to replicate using the metadata param from #72, unless I'm missing something. Some of them will need to be included in the metadata anyway because they're also used by the flow and amplitude metrics, e.g. template name. So if we add headers as well it means we're setting things in two places, which feels like wilfully setting out to cause confusion in the future.

**Comment by philbooth** [comment]
(of course I might still be misunderstanding how some of this works, definitely set me straight if I'm missing something here)

**Comment by vladikoff** [comment]
Sounds good, @brizental let's stop working on this for now, but backup the branch because I have a feeling we might need to come back to this later...

**Comment by vbudhram** [comment]
FWIW, I think adding custom headers is still worthwhile since we use it on our automated tests. Not to say that we can't update the tests but there might be a good amount of churn to make sure everything is working as expected.

**Comment by philbooth** [comment]
> I think adding custom headers is still worthwhile...

Understood. Obviously this repo is not a dictatorship, so if I'm in the minority then you guys can add it. I'll cope! 😄

But, for the record, I'm as strongly -1 to it as a design decision as it's possible to be.

**Comment by shane-tomlinson** [comment]
I have been trying to think through the pros and cons of using Redis vs using the email headers since this issue popped up last week. @philbooth I'd like to hear more about why headers are a bad idea. I can intuitively understand the pro-header argument but feel uninformed about why we shouldn't use them. I'd like to understand the tradeoffs for both.

Headers seem like the easy option because we already use them. Using Redis requires Ops to stand up and maintain a new Redis instance. If we were to use a Redis instance to store metadata, would we store metadata for *all* emails within Redis or only a subset, e.g., only restmail.com addresses? If all email addresses, are there security repercussions we haven't thought through? Does sending to Redis in addition to sending to the email service complicate email sending? Does using Redis complicate automated tests since we'd have to query two servers, first check the email was sent, and then pull metadata from Redis? Does using Redis just shift complexity - the fxa-email-sender is simplified but the auth-server and content-server shoulder the complexity?

> I think adding custom headers is still worthwhile since we use it on our automated tests.

For better or worse the headers are now part of our public API. Other teams within Mozilla pull verification URLs out of the emails, and I'm not sure whether they parse the emails or whether they make use of the headers. We'd have to ask AMO and the automated testing teams before changing the API unless we want to be chased by angry mobs with pitchforks.

**Comment by philbooth** [comment]
> I'd like to hear more about why headers are a bad idea

Tbh, I don't think we need to draw this discussion out any longer. I recognise that the team collectively disagrees with my opinion but that's okay, it's part of being in a team sometimes. As I already said, if you guys want to add them please go ahead and I promise not to complain about it! 😄

But fwiw, since you ask, this is where I'm coming from:

1. This repo needs storage of some form in order to function, it's not possible to implement it statelessly (see the [feature doc](https://docs.google.com/document/d/1SZ_uGpqofUJeOjGAu2oRKqp-qEMLbvWt8UlxK4UbFwI) and https://github.com/mozilla/fxa-email-service/issues/4#issuecomment-394076137 for more discussion about this).

   Right now, the state just lives in the auth db because that's the simplest migration path from what we already have, but for our long-term plan of a standalone service it's not an option. So regardless of the outcome here, there is going to be some kind of data store associated with this repo.

2. The entire raison d'être for this repo is to abstract away implementation details of the underlying provider, to enforce loose coupling. It's a foundational principle of the API not to directly expose any of those implementation details.

   Email headers can obviously be directly interpreted by the email provider, so to my mind they are ipso facto an implementation detail that should not be exposed. If an underlying provider implements behaviour that can be controlled by an email header, that behaviour leaks out of our abstraction by exposing the headers. Why are we going to the trouble of hiding providers behind generic traits in the code, if the API bypasses them?

3. Storing our own data in-house seems vastly preferable to sending it off to third parties, for reasons that are hopefully obvious. What safeguards are in place to stop us from accidentally leaking sensitive information in an email header? We've made that kind of mistake before.

So, with all that in mind, these would be my counter-arguments to your list of "pros" in favour of exposing headers:

> Headers seem like the easy option because we already use them.

I'm less concerned with doing what's easy than with doing what's right. If we choose to expose email headers because we think it's the right decision, I'd be happier than if we choose it because it's easier.

> Using Redis requires Ops to stand up and maintain a new Redis instance.

We need storage in this repo anyway. And again, it's the "what's easy vs what's right" debate.

> If we were to use a Redis instance to store metadata, would we store metadata for all emails within Redis or only a subset, e.g., only restmail.com addresses?

That's up to the caller, if metadata is sent we store it, otherwise we don't. In practical terms that means for all emails initially, because the auth server is the only caller and it emits metrics for all emails.

> If all email addresses, are there security repercussions we haven't thought through?

Quite possibly. But is your suggestion that it's more secure to send that data to a third party than it is to store it in-house? The opposite seems true to me.

> Does sending to Redis in addition to sending to the email service complicate email sending?

I can't think of anything about it that is more complicated, but if you have something in mind I'd be interested to hear it.

> Does using Redis complicate automated tests since we'd have to query two servers, first check the email was sent, and then pull metadata from Redis?

No, absolutely not. Why would automated tests outside this repo need to assert what it does internally? Surely only the tests in this repo should be concerned with that?

I've been trying to work out specifically which tests you're worried about here, is it the functional tests in the content server? Because they make assertions against the content of received email bodies or something?

Hopefully it goes without saying that I'm putting my hand up to implement equivalent functionality that allows all existing tests to pass, as part of migrating to the new service. But even in a worst case scenario, if something is physically impossible, nothing prevents us from using the old mail helper code for those tests. It's already a different path of execution than SES at the moment, so it's not like the tests would be further compromised by continuing to use it (imho).

> Does using Redis just shift complexity - the fxa-email-sender is simplified but the auth-server and content-server shoulder the complexity?

My aim is the complete opposite of that, to remove complexity from the auth server and localise it in a single, small, well-tested unit.

**Comment by rfk** [comment]
> This repo needs storage of some form in order to function

I'll add that, I recall it being difficult-to-impossible to implement the "tunnel data to the bounce notification by putting it in headers" hack on top of sendgrid, because the webhooks don't give you back the headers.  I could be wrong on the specifics, but I think it's true in general that we don't want to depend on service-specific hacks like that.

> I've been trying to work out specifically which tests you're worried about here,
> is it the functional tests in the content server?

One example of tests that depend on email headers are those in PyFxA, such as:

  https://github.com/mozilla/PyFxA/blob/master/fxa/tests/test_core.py#L110

We use email headers for a few different things, and I expect we will want to keep some but not all of those uses:

* For tunneling metadata through bounce notifications, e.g. `X-Flow-Id` and friends.  This is SES-specific and I agree with @philbooth that it's better to handle that explicitly and generically via a "metadata storage" in this service.
* For easier machine parsing of received emails, e.g. `X-Verify-Code` and friends.  I don't think we can lose this functionality without widespread test bustage, including in code that we don't directly control, so we'll need to keep it somehow.
* For whatever operational purposes `X-SES-CONFIGURATION-SET` and friends enable, which I don't really recall, but are clearly SES-specific and so should be replaced with some more generic mechanism provided by this repo.

@vladikoff's suggestion of an allowlist seems like a good start to me, although if we can find an alternative for `X-SES-CONFIGURATION-SET` then I think we could.

Thinking forward to the future, perhaps we'd be more comfortable allowing only headers with a mozilla-specific prefix, such as "X-Moz-BlahBlah" or similar, so that we can be confident they won't trigger any provider-specific behaviour?

**Comment by philbooth** [comment]
> One example of tests that depend on email headers are those in PyFxA, such as:
>
> https://github.com/mozilla/PyFxA/blob/master/fxa/tests/test_core.py#L110

Ah, thanks, that makes sense. It's exactly what I was looking for when I was asking "why" earlier in the thread. I understand what this issue is for now.

> * Content-Language

And this is another example that might have persuaded me if someone had mentioned it earlier.

> * X-SES-CONFIGURATION-SET
> * X-SES-MESSAGE-TAGS

Just as a +1 to Ryan's point, these two are explicitly discussed in the [feature doc](https://docs.google.com/document/d/1SZ_uGpqofUJeOjGAu2oRKqp-qEMLbvWt8UlxK4UbFwI) as an example of coupling that we're trying to eradicate. Although I'm a big believer that plans should change with time, I also think we should at least make an attempt to adhere to them and provide some justification when they do change. Is there a justification for exposing these?

> * X-Template-Name
> * X-Template-Version

Aren't these only used by the metrics? Can we move them into the other list? They'll already be set in the `metadata` param, so if we can avoid setting them twice I'd be happier.

**Comment by philbooth** [comment]
> Is there a justification for exposing these?

They come from config I notice. If we just move that config into this repo as part of the `Aws` struct in `src/settings/mod.rs`, then it becomes an implementation detail of the SES provider.

**Comment by vladikoff** [comment]
Some thoughts:

- [ ] Create an allow list of headers, log an error if an unknown header appears 
- [ ] Follow up issue: move the X-SES header to this service. Migrate code from auth-server
- [ ] Handle known headers that pass through and those that do not. Log an error when an unknown header gets sent to we can debug it....

**Comment by vladikoff** [comment]
> > X-Template-Name
> > X-Template-Version

> Aren't these only used by the metrics? Can we move them into the other list?

@jrgm uses x-template-name in AWS metrics to see it in the cloudwatch graph, we can drop TemplateVersion if you want, but I don't think that is a big deal, that value can also be useful in cloudwatch if we bump or have different versions of templates...
